services:
  - type: web
    name: truemeter-frontend
    runtime: docker
    repo: https://github.com/Zoran-Janjic/truemeter-frontend.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://truemeter-api.onrender.com
    plan: free
